---
# ArgoCD Application для HashiCorp Vault (k3s + Traefik)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: "0.32.0"
    helm:
      values: |
        global:
          enabled: true

        server:
          enabled: true

          # Простая single-node установка (без HA), удобно для домашнего/k3s
          ha:
            enabled: false

          # Включаем UI Vault
          ui:
            enabled: true
            serviceType: ClusterIP

          # Ingress под Traefik в k3s
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: "selfsigned-issuer"
              traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
            hosts:
              - host: vault.lab-home.com
                paths:
                  - /
            tls:
              - secretName: vault-tls
                hosts:
                  - vault.lab-home.com

          # Постоянное хранилище данных Vault (PV/PVC)
          dataStorage:
            enabled: true
            size: 5Gi
            # Для k3s обычно используется storageClass "local-path".
            # Можно поставить null, чтобы использовать storageClass по умолчанию.
            storageClass: local-path
            accessMode: ReadWriteOnce

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

