---
# ArgoCD Application для qBittorrent
# qBittorrent - BitTorrent клиент для загрузки медиафайлов
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  # Источник - Kustomize из Git репозитория
  source:
    repoURL: https://github.com/mistermedved01/k3s-test.git
    targetRevision: HEAD
    path: argocd-apps/media-server-stack/qbittorrent
  
  # Назначение - текущий кластер, namespace radarr (общий с Radarr для shared downloads)
  destination:
    server: https://kubernetes.default.svc
    namespace: radarr
  
  # Политика синхронизации
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions: []
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
