---
# Certificate для MinIO Tenant Console (TLS на входе Traefik)
# cert-manager создаёт Secret minio-tenant-console-tls для Ingress/IngressRoute
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-tenant-console-tls
  namespace: minio-operator
spec:
  secretName: minio-tenant-console-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - minio.lab.local
