---
# MinIO Tenant CRD
# Определяет MinIO кластер (хранилище)
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio-tenant
  namespace: minio-operator
  labels:
    app: minio
spec:
  # Количество серверов (для standalone используем 1, для distributed минимум 4)
  pools:
    - name: pool-0
      servers: 1
      volumesPerServer: 1
      # Ресурсы для MinIO серверов в пуле
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 2000m
          memory: 2Gi
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: local-path
          resources:
            requests:
              storage: 10Gi
  
  # Configuration для доступа к MinIO
  # Secret должен содержать config.env с MINIO_ROOT_USER и MINIO_ROOT_PASSWORD
  configuration:
    name: storage-configuration
  
  # Версия MinIO сервера (2023 для совместимости со старыми CPU)
  image: minio/minio:RELEASE.2023-09-04T19-57-37Z
  
  # Настройки для экспорта сервисов
  exposeServices:
    minio: true   # Внутренний Service для S3 API
    console: true # Внутренний Service для Console

---
# Secret для configuration
# Содержит credentials для MinIO Tenant
apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
  namespace: minio-operator
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER=minioadmin
    export MINIO_ROOT_PASSWORD=minioadmin123
    export MINIO_BROWSER=on
    # Примечание: В production используйте безопасные пароли!