---
# ArgoCD Application для Homepage
# Homepage - современная домашняя страница/дашборд для самохостинга
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  # Источник - Kustomize из Git репозитория
  source:
    repoURL: https://github.com/mistermedved01/lab-home.git
    targetRevision: HEAD
    path: 03-argocd/homepage
  
  # Назначение - текущий кластер, namespace homepage
  destination:
    server: https://kubernetes.default.svc
    namespace: homepage
  
  # Политика синхронизации
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
