---
# ArgoCD Application для Prowlarr
# Prowlarr - менеджер источников медиаконтента для организации личной коллекции видео
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  # Источник - Kustomize из Git репозитория
  source:
    repoURL: https://github.com/mistermedved01/k3s-test.git
    targetRevision: HEAD
    path: argocd-apps/media-server-stack/prowlarr
  
  # Назначение - текущий кластер, namespace prowlarr
  destination:
    server: https://kubernetes.default.svc
    namespace: prowlarr
  
  # Политика синхронизации
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
